# services:
#   nginx:
#     image: nginx:1.27-alpine
#     container_name: reverse-nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - proj1_static1:/static/proj1:ro
#       - proj1_media1:/media/proj1:ro
#       - proj2_static:/static/proj2:ro
#       - proj2_media:/media/proj2:ro
#     networks: [proxy_net]
#     restart: unless-stopped

# networks:
#   proxy_net:
#     external: true

# volumes:
#   proj1_static1:
#     external: true
#   proj1_media1:
#     external: true
#   proj2_static:
#     external: true
#     name: proj2_static
#   proj2_media:
#     external: true
#     name: proj2_media
services:
  nginx:
    image: nginx:1.27-alpine
    container_name: reverse-nginx
    ports:
      - "80:80"
      - "443:443"                 # <— добавили HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - proj1_static1:/static/proj1:ro
      - proj1_media1:/media/proj1:ro
      - proj2_static:/static/proj2:ro
      - proj2_media:/media/proj2:ro
      - certbot-www:/var/www/certbot         # <— webroot для ACME
      - letsencrypt:/etc/letsencrypt         # <— сами сертификаты
    networks: [proxy_net]
    restart: unless-stopped

  # вспомогательный сервис для выдачи/продления сертификатов
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    entrypoint: /bin/sh
    command: -c "sleep infinity"

networks:
  proxy_net:
    external: true

volumes:
  proj1_static1:
    external: true
  proj1_media1:
    external: true
  proj2_static:
    external: true
    name: proj2_static
  proj2_media:
    external: true
    name: proj2_media
  certbot-www:               # <— добавили
  letsencrypt:               # <— добавили
