services:
  nginx:
    image: nginx:1.27-alpine
    container_name: reverse-nginx
    ports: ["80:80"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # те же имена томов:
      - static1:/static/proj1:ro
      - media1:/media/proj1:ro
      # если нужен proj2 — добавь его тома аналогично
    networks: [proxy_net]
    restart: unless-stopped

networks:
  proxy_net:
    external: true

volumes:
  static1:
    external: true
  media1:
    external: true
