services:
  nginx:
    image: nginx:1.27-alpine
    container_name: reverse-nginx
    ports:
      - "80:80"
      # - "443:443"  # если добавишь HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy_net
    restart: unless-stopped

networks:
  proxy_net:
    external: true
